---
# TODO: restart services only if their config file changed, not all services when only one changed
- name: Install NUT configuration files for server.
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/nut/{{ item }}"
    owner: "root"
    group: "nut"
    mode: "0640"
  loop:
    - ups.conf
    - upsd.conf
    - upsd.users
    - upsmon.conf
    - upssched.conf
    - nut.conf
  notify: restart_nut_server
  when: nut_instance_is_server | bool

- name: Install NUT configuration files for client.
  template:
    src: "templates/{{ item }}.j2"
    dest: "/etc/nut/{{ item }}"
    owner: "root"
    group: "nut"
    mode: "0640"
  loop:
    - upsmon.conf
    - upssched.conf
    - nut.conf
  notify: restart_nut_client
  when: not nut_instance_is_server | bool

- name: Remove server configuration from clients.
  file:
    path: "/etc/nut/{{ item }}"
    state: absent
  loop:
    - ups.conf
    - upsd.conf
    - upsd.users
  notify: restart_nut_client
  when: not nut_instance_is_server | bool
