---
- name: Restart nut-driver
  ansible.builtin.service:
    name: nut-driver
    state: restarted
  become: true
  listen:
    - restart_nut_server
    - restart_nut_driver_service
  failed_when: false

- name: Restart nut-server
  ansible.builtin.service:
    name: nut-server
    state: restarted
  become: true
  listen:
    - restart_nut_server
    - restart_nut_server_service

- name: Restart nut-monitor
  ansible.builtin.service:
    name: nut-monitor
    state: restarted
  become: true
  listen:
    - restart_nut_client
    - restart_nut_server
    - restart_nut_monitor_service

- name: Restart nut-client
  ansible.builtin.service:
    name: nut-client
    state: restarted
  become: true
  listen:
    - restart_nut_client
    - restart_nut_server
    - restart_nut_client_service

# - name: Restart nut-driver-enumerator
#   service:
#     name: "nut-driver-enumerator"
#     state: restarted
#   become: true
#   listen:
#     - restart_nut_all
#     - restart_nut_driver_enumerator
